-- =============================================================================
-- FILE: 08_audit_test_actions.sql
-- ĐỀ TÀI: ĐỒ ÁN AN TOÀN BẢO MẬT HỆ THỐNG THÔNG TIN
-- CHỨC NĂNG:
--   - Chạy các câu lệnh test thử nghiệm (gồm hành động hợp pháp và bất hợp pháp)
--     để hệ thống Oracle phát sinh log kiểm toán (Audit Log).
--   - Đăng nhập dưới dạng các user BS001, KTV01, BN000001 để:
--     + Xem/sửa hồ sơ bệnh án, đơn thuốc, cập nhật kết quả dịch vụ đúng vai trò.
--     + Gọi thử thủ tục P_AUDIT_DEMO_MARK và hàm F_AUDIT_DEMO_USER.
--     + Thực hiện các hành vi bất hợp pháp (ví dụ: Bệnh nhân cố tình sửa HSBA,
--       xóa chỉ định dịch vụ).
-- TÀI KHOẢN THỰC THI: CONNECT chuyển đổi linh hoạt qua lệnh SQL*Plus (SYS, BS001, KTV01, BN000001).
-- THỨ TỰ THỰC THI: Chạy sau khi đã cấu hình Audit thành công (Bước 8).
-- =============================================================================

SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR CONTINUE;

PROMPT ===== 1. USER BS001 - TEST UA_CQ09_VIEW_SUCCESS / FGA_CQ09_HSBA_UPDATE =====
PROMPT Ky vong: SELECT/UPDATE qua CQ09.VW_BACSI_HSBA thanh cong, RETURN_CODE = 0.
PROMPT FGA ky vong: UPDATE CHANDOAN/DIEUTRI/KETLUAN tren HSBA tao FGA_CQ09_HSBA_UPDATE.
CONNECT BS001/ATBM123@localhost:1521/XEPDB1

PROMPT [BS001][UA_CQ09_VIEW_SUCCESS] SELECT CQ09.VW_BACSI_HSBA - EXPECT SUCCESS.
SELECT MAHSBA, MABN, TENBN, NGAY, CHANDOAN, DIEUTRI, KETLUAN
FROM CQ09.VW_BACSI_HSBA
WHERE MAHSBA = 'HSBA2024001';

PROMPT [BS001][UA_CQ09_VIEW_SUCCESS + FGA_CQ09_HSBA_UPDATE] UPDATE CQ09.VW_BACSI_HSBA - EXPECT SUCCESS.
UPDATE CQ09.VW_BACSI_HSBA
SET CHANDOAN = N'AUDIT21C BS001 - cap nhat chan doan hop le',
    DIEUTRI  = N'AUDIT21C BS001 - cap nhat dieu tri hop le',
    KETLUAN  = N'AUDIT21C BS001 - cap nhat ket luan hop le'
WHERE MAHSBA = 'HSBA2024001';

PROMPT ===== 2. USER BS001 - TEST UA_CQ09_TABLE_SUCCESS / UA_CQ09_VIEW_SUCCESS / FGA_CQ09_DONTHUOC_UPDATE =====
PROMPT Ky vong: SELECT bang DONTHUOC va UPDATE qua VW_BACSI_DONTHUOC thanh cong, RETURN_CODE = 0.
PROMPT FGA ky vong: UPDATE LIEUDUNG tren DONTHUOC tao FGA_CQ09_DONTHUOC_UPDATE.

PROMPT [BS001][UA_CQ09_TABLE_SUCCESS] SELECT CQ09.DONTHUOC - EXPECT SUCCESS.
SELECT MAHSBA, NGAYDT, TENTHUOC, LIEUDUNG
FROM CQ09.DONTHUOC
WHERE MAHSBA = 'HSBA2024001'
  AND ROWNUM <= 5;

PROMPT [BS001][UA_CQ09_VIEW_SUCCESS + FGA_CQ09_DONTHUOC_UPDATE] UPDATE CQ09.VW_BACSI_DONTHUOC - EXPECT SUCCESS.
UPDATE CQ09.VW_BACSI_DONTHUOC
SET LIEUDUNG = N'AUDIT21C BS001 - cap nhat lieu dung hop le'
WHERE MAHSBA = 'HSBA2024001'
  AND NGAYDT = DATE '2024-01-10'
  AND TENTHUOC = N'Metformin 1000mg';

PROMPT ===== 3. USER BS001 - TEST UA_CQ09_PROC_EXEC / UA_CQ09_FUNC_EXEC =====
PROMPT Ky vong: EXECUTE procedure/function demo thanh cong, RETURN_CODE = 0.

PROMPT [BS001][UA_CQ09_PROC_EXEC] EXECUTE CQ09.P_AUDIT_DEMO_MARK - EXPECT SUCCESS.
BEGIN
    CQ09.P_AUDIT_DEMO_MARK('BS001 test UA_CQ09_PROC_EXEC');
END;
/

PROMPT [BS001][UA_CQ09_FUNC_EXEC] EXECUTE CQ09.F_AUDIT_DEMO_USER - EXPECT SUCCESS.
SELECT CQ09.F_AUDIT_DEMO_USER() AS SESSION_USER_FROM_FUNCTION
FROM dual;

COMMIT;

PROMPT ===== 4. USER BS002 - TEST UA_CQ09_FAILED_ATTEMPTS =====
PROMPT Ky vong: DELETE truc tiep CQ09.HSBA that bai voi ORA-01031, RETURN_CODE <> 0.
PROMPT Ghi chu: khong dung UPDATE qua view nham dong ngoai pham vi vi VPD co the chi lam 0 rows affected.
CONNECT BS002/ATBM123@localhost:1521/XEPDB1

PROMPT [BS002][UA_CQ09_FAILED_ATTEMPTS] DELETE CQ09.HSBA - EXPECT ORA-01031.
DELETE FROM CQ09.HSBA
WHERE MAHSBA = 'HSBA2024001';

PROMPT [BS002][UA_CQ09_FAILED_ATTEMPTS] UPDATE CQ09.VW_KTV_HSBA_DV - EXPECT ORA-00942/ORA-01031.
UPDATE CQ09.VW_KTV_HSBA_DV
SET KETQUA = N'AUDIT21C BS002 - co tinh sua ket qua KTV'
WHERE MAHSBA = 'HSBA2024001';

ROLLBACK;

PROMPT ===== 5. USER KTV01 - TEST UA_CQ09_VIEW_SUCCESS =====
PROMPT Ky vong: SELECT/UPDATE KETQUA qua CQ09.VW_KTV_HSBA_DV thanh cong, RETURN_CODE = 0.
CONNECT KTV01/ATBM123@localhost:1521/XEPDB1

PROMPT [KTV01][UA_CQ09_VIEW_SUCCESS] SELECT CQ09.VW_KTV_HSBA_DV - EXPECT SUCCESS.
SELECT MAHSBA, LOAIDV, NGAYDV, MAKTV, KETQUA
FROM CQ09.VW_KTV_HSBA_DV
WHERE ROWNUM <= 5;

PROMPT [KTV01][UA_CQ09_VIEW_SUCCESS] UPDATE KETQUA tren CQ09.VW_KTV_HSBA_DV - EXPECT SUCCESS.
UPDATE CQ09.VW_KTV_HSBA_DV
SET KETQUA = N'AUDIT21C KTV01 - cap nhat ket qua hop le'
WHERE MAHSBA = 'HSBA2024001'
  AND NGAYDV = DATE '2024-01-10';

COMMIT;

PROMPT ===== 6. USER KTV02 - TEST UA_CQ09_FAILED_ATTEMPTS =====
PROMPT Ky vong: thao tac truc tiep ngoai quyen role RL_KYTHUATVIEN that bai voi ORA-01031, RETURN_CODE <> 0.
PROMPT Ghi chu: khong dung thao tac qua view phu thuoc VPD loc dong.
CONNECT KTV02/ATBM123@localhost:1521/XEPDB1

PROMPT [KTV02][UA_CQ09_FAILED_ATTEMPTS] UPDATE CQ09.HSBA - EXPECT ORA-00942/ORA-01031.
UPDATE CQ09.HSBA
SET CHANDOAN = N'AUDIT21C KTV02 - co tinh sua chan doan'
WHERE MAHSBA = 'HSBA2024001';

PROMPT [KTV02][UA_CQ09_FAILED_ATTEMPTS] DELETE CQ09.HSBA_DV - EXPECT ORA-01031.
DELETE FROM CQ09.HSBA_DV
WHERE MAHSBA = 'HSBA2024001';

ROLLBACK;

PROMPT ===== 7. USER BN000001 - TEST UA_CQ09_VIEW_SUCCESS =====
PROMPT Ky vong: SELECT/UPDATE thong tin ca nhan qua CQ09.VW_BENHNHAN thanh cong, RETURN_CODE = 0.
CONNECT BN000001/ATBM123@localhost:1521/XEPDB1

PROMPT [BN000001][UA_CQ09_VIEW_SUCCESS] SELECT CQ09.VW_BENHNHAN - EXPECT SUCCESS.
SELECT MABN, TENBN, SONHA, TENDUONG, QUANHUYEN, TINHTP
FROM CQ09.VW_BENHNHAN;

PROMPT [BN000001][UA_CQ09_VIEW_SUCCESS] UPDATE CQ09.VW_BENHNHAN - EXPECT SUCCESS.
UPDATE CQ09.VW_BENHNHAN
SET SONHA = '12A',
    TENDUONG = N'AUDIT21C BN000001 - cap nhat dia chi hop le'
WHERE MABN = 'BN000001';

COMMIT;

PROMPT ===== 8. USER BN000001 - TEST UA_CQ09_FAILED_ATTEMPTS =====
PROMPT Ky vong: UPDATE CQ09.HSBA va DELETE CQ09.HSBA_DV truc tiep that bai voi ORA-01031, RETURN_CODE <> 0.

PROMPT [BN000001][UA_CQ09_FAILED_ATTEMPTS] UPDATE CQ09.HSBA - EXPECT ORA-01031.
UPDATE CQ09.HSBA
SET CHANDOAN = N'AUDIT21C BN000001 - co tinh sua chan doan'
WHERE MAHSBA = 'HSBA2024001';

PROMPT [BN000001][UA_CQ09_FAILED_ATTEMPTS] DELETE CQ09.HSBA_DV - EXPECT ORA-01031.
DELETE FROM CQ09.HSBA_DV
WHERE MAHSBA = 'HSBA2024001';

PROMPT ===== 6. DOC LOG AUDIT SAU TEST =====
PROMPT Hay chay 09_audit_read_logs.sql bang CQ09.

WHENEVER SQLERROR EXIT;
